---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}

library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>%
  mutate(rating = review_scores_location / 2) %>%
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>%
  drop_na(rating)

nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

nyc_airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  plot_ly(
    y = ~price, x = ~neighbourhood, color = ~neighbourhood, 
    type = "box", colors = "viridis")

```

### Chart C

```{r}

nyc_airbnb %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood, 
    type = "bar", colors = "viridis")

```

to render the dashboad correctly, need to either remake entire website or use direct command in command
line: [rmarkdown::render("dashboard_template.Rmd", output_format = "flexdashboard::flex_dashboard")]




